### ISSUE TITLE
Plugin not enabled

### ISSUE THREAD

**Issue by didierm** [Chaosmeister/SubtaskResult#1]
Dear,
thanks for your efforts.

Issue : 
after manually installing (it is not listed in KB's "Plugin Directory") the plugin in the latest KB v1.2.36, it is not visible in the list of  "Installed Plugins", neither is the comment field available when editing a subtask.

No PHP errors are emitted.

**Comment by Chaosmeister** [comment]
Hey sorry for the late response,

> it is not visible in the list of "Installed Plugins"

I can't reproduce this with the latest versions of the plugin and kanboard

> neither is the comment field available when editing a subtask.

that is by design.  
This plugin is basically deprecated by my [dod plugin](https://github.com/Chaosmeister/DefinitionOfDone)

**Comment by didierm** [comment]
After upgrading KB to latest v1.2.42 en enabling debug logs, the following error is emitted (causing the plugin to not be displayed in the list of installed plugins) : 
```
SubtaskResult: Unable to migrate schema for the plugin: SubtaskResult => SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "`"
LINE 4:             `text` TEXT,
```

This is due to backticks being used in `SubtaskResult/Schema/Postgres.php` ; fix : 
```
@@ -13,3 +13,3 @@
             id INT,
-            `text` TEXT,
+            'text' TEXT,
             CONSTRAINT subtaskResult FOREIGN KEY (id) REFERENCES subtasks(id) ON DELETE CASCADE
```

_(note : backticks are also used in Mysql.php ; not sure whether this is valid MySQL/MariaDB syntax)_

**Comment by Chaosmeister** [comment]
aha!
that's an easy fix
